<?php
/**
 * @project: CartImport
 * @author : LitExtension
 * @url    : http://litextension.com
 * @email  : litextension@gmail.com
 */
?>
<div class="section_guide">
    <!--
    <p>Please export your Nopcommerce data to XML file and upload it in fields below.</p>
    <strong>Proceed with the following steps for required data tables:</strong>
    <ol style="list-style: square; padding-left: 20px;">
        <li>Sign in to your Nopcommerce admin account.</li>
        <li><b>Categories</b>:Go to <b>Catalog -&gt; Categories -&gt; List</b> and click on <b>"Export to XML"</b> button.</li>
        <li><b>Manufacturer</b>:Go to <b>Catalog -&gt; Manufacturers</b> and click on <b>"Export to XML"</b> button.</li>
    <li><b>Customers</b>:Go to <b>Customers -&gt; Customers -&gt;</b> and:<br>
        -Click on <b>"Export to XML(all found)"</b> button to export all customers.<br>
        -Check the customer IDs which you want to export and then click on <b>"Export to XML(selected)"</b> button to export selected customers.
    </li>
    <li><b>Products</b>:Go to <b>Catalog -&gt; Products -&gt; Manage Products</b> and:<br>
        - Click on <b>"Export to XML(all found)"</b> button to export all products.<br>
        - Check the product IDs which you want to export and then click on <b>"Export to XML(selected)"</b> button to export selected products.
    </li>
    <li><b>Orders</b>:Go to <b>Sales -&gt; Orders </b> and:<br>
        - Click on <b>"Export to XML(all found)"</b> button to export all orders.<br>
        - Check the order IDs which you want to export and then click on <b>"Export to XML(selected)"</b> button to export selected orders.
    </li>
        <li>Upload saved file in the corresponding field below.</li>
        <li>Please note if the size of downloaded XML file exceeds <?php echo ini_get('upload_max_filesize'); ?>B limit (<a href="https://www.google.com/search?q=change+php+upload+file+size" target="_blank">How to change this limit</a>)</li>
    </ol>
-->
</div>